query charactersQuery($page: Int!, $filter: String) {
  characters(filter: { name: $filter }, page: $page) {
    results {
      image
      id
      name
      gender
      species
      status
      episode {
        episode
      }
    }
  }
}
